server:
  port: 8989

spring:
  application:
    name: config-client
  cloud:
    config:
#      uri: http://localhost:8888/
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: spring-cloud-config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:123456localhost:8000}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'